### ISSUE TITLE
Create PostListRow component

### ISSUE THREAD

**Issue by nilaymaj** [pclubiitk/Campus-Discuss-App#1]
Create a component that represents a single row of a list of posts (see user feed screen or stream home screen design). The component should take (at least) the following as props:
- A `post` object of type `IPost`. This object contains all data of the post and its author.
- An `onPress` function of type `() => void`. Call this function when the user taps the row.

[`ListItem`](https://react-native-elements.github.io/react-native-elements/docs/listitem.html) from React Native Elements seems like a good fit for this component. You can display the author name and the date of the post in the subheader. 

Also, the backend does not have profile picture support right now, so display the author name's first letter in the avatar.

**Comment by 7shivamx** [comment]
I'm taking up this issue

**Comment by kartikcode** [comment]
Fixed with #23
