### ISSUE TITLE
Create StreamDescriptionOverlay component

### ISSUE THREAD

**Issue by nilaymaj** [pclubiitk/Campus-Discuss-App#3]
Create a component for the stream description overlay that is to be shown when the user taps on a stream on the Explore streams screen. As props, take:
- A boolean `open`, that decides if the overlay is open or not.
- A `stream` object of type `IStream`.
- A boolean that specifies if the stream is followed by the user or not.
- An `onButtonPress` function of type `() => void`: call this function when the user taps on the Subscribe (or Unsubscribe) button.

[`Overlay`](https://react-native-elements.github.io/react-native-elements/docs/overlay.html) from React Native Elements seems good for making this.

**Comment by diyasinghal21** [comment]
Diya Singhal and Shivam Malhotra are taking up this issue.

**Comment by BipplavTiwari** [comment]
Bipplav Kumar Tiwari and Sriramchandher are taking up this issue
