### ISSUE TITLE
Create the sidebar component

### ISSUE THREAD

**Issue by nilaymaj** [pclubiitk/Campus-Discuss-App#4]
Create the component for the app's sidebar. You'll need the following data:
- The user profile: an object of type `IUserData`.
- List of subscribed streams: an array with elements of type `IStream`.

For now, take these as props. Later when we create the Redux store, we'll modify the code to use that.

**Comment by navyagurugubelli** [comment]
I will be working on this issue

**Comment by kartikcode** [comment]
Fixed with #20
