### ISSUE TITLE
Create FullPost component

### ISSUE THREAD

**Issue by nilaymaj** [pclubiitk/Campus-Discuss-App#5]
Create a component for displaying the full post - this will be used for the view post screen.
You'll need two props:
- A `post` object of type `IPost`
- An `onOpenComments` function of type `() => void`: call this function when the user taps on the button for opening the comments section.

**Comment by devanshusingla** [comment]
I am taking this issue

**Comment by 7shivamx** [comment]
I will be working on this issue

**Comment by kartikcode** [comment]
Fixed with #24 .
