### ISSUE TITLE
Create CommentsOverlay component

### ISSUE THREAD

**Issue by nilaymaj** [pclubiitk/Campus-Discuss-App#6]
Create a component for the comments section overlay. As props, take:
- An `open` boolean that decides whether the overlay is open or not.
- `comments`: an array of objects of type `IComment`.

You can add any other props that may be necessary.

**Comment by devanshusingla** [comment]
I am taking this task

**Comment by asharma8602** [comment]
Ashutosh and Abhinav are taking up this issue

**Comment by nilaymaj** [comment]
Feel free to look at and use the existing PR. I think you should be able to pull from the PR to your branch and make additional changes if any. You can start from scratch too if you want, no problem.

**Comment by kartikcode** [comment]
Fixed with #19
