### ISSUE TITLE
Create Profile component

### ISSUE THREAD

**Issue by nilaymaj** [pclubiitk/Campus-Discuss-App#7]
Create a component that shows the profile of the user - to be used for the Profile screen.
As props, take:
- A `profile` object of type `IUserData`
- An `onLogout` function of type `() => void`: call this function when the user taps on the logout button.

Keep the username and fblink fields as editable.

**Comment by kartikcode** [comment]
I'll take this one.

**Comment by sarthak759** [comment]
we are taking this issue

**Comment by sarthak759** [comment]
sarthak goyal, anushka panda and shivam mishra are taking this issue
